---
# tasks file for jenkins
- name: Import GPG key
  rpm_key:
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present

- name: Create Jenkins repository
  yum_repository:
    name: Jenkins
    description: Jenkins repository
    baseurl: http://pkg.jenkins.io/redhat
    enabled: yes
    gpgcheck: yes

- name: Install Java 8
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present
  
- name: Install git
  yum:
    name: git
    state: present

- name: Set Java 8 as the default
  command: /usr/sbin/alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start the Jenkins service and ensure that it gets started on system book
  service:
    name: jenkins
    state: started
    enabled: yes


